version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('SCRIPT_DEBUG', true);
    volumes:
      - wordpress_data:/var/www/html
      - ./wp-content/plugins/medal-map:/var/www/html/wp-content/plugins/medal-map
      - ./images:/var/www/html/wp-content/plugins/medal-map/images
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini  # Mount Xdebug config
    depends_on:
      db:
        condition: service_healthy
    networks:
      - medal_map_network

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "3306:3306"
    networks:
      - medal_map_network

  wp-cli:
    image: wordpress:cli-2.9
    depends_on:
      wordpress:
        condition: service_started
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress_data:/var/www/html
      - ./scripts:/scripts
    working_dir: /var/www/html
    networks:
      - medal_map_network
    command: tail -f /dev/null

volumes:
  wordpress_data:
  mysql_data:

networks:
  medal_map_network:
    driver: bridge
